services:
  - type: web
    name: covoiturage-suisse-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start_render.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: "true"
